<?php
session_start();
$message=$_SESSION['message'];
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title> Welcome</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/welcome.css">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="mid-section">
    </div>

    <section class="content2-page">


  <h1 class="sales">Sales</h1>
  <div class="sales-container">
<canvas id="myChart"></canvas>
  </div>

<h1 class="costs">Costs</h1>
  <div class="costs-container">
<canvas id="costChart"></canvas>
  </div>






    </section>



    <div class="footer">
  <div class="email-section">
    <a href="index.html" class="logo">Owl Digital</a>
    <ul class="footer-menu">
        <li> <a href="register.php"> Create Account</a>
        </li>
        <li> <a href="login.php">Logout</a>
        </li>
    </ul>
    <div class="footer-icons">
<div class="footer-copyright">
<h1>@Owl Digital</h1>
  <!-- <div >Logo generated by <a href="https://www.designevo.com/logo-maker/" title="Free Online Logo Maker">DesignEvo free logo designer</a></div> -->
</div>
    </div>
  </div>

    </div>
    <script>
    //////////////////////////////////hamburger-menu////////////////////////////
    // const menuBtn=document.querySelector('.menu-btn');
    // const navmenu=document.querySelector('.nav-links');
    //
    // let menuOpen=false;
    // menuBtn.addEventListener('click',function(){
    //   if(!menuOpen){
    // menuBtn.classList.add('open');
    // navmenu.classList.add('clicked');
    //     menuOpen=true;
    //      }
    //   else
    //   {
    //   menuBtn.classList.remove('open');
    //   navmenu.classList.remove('clicked');
    //     menuOpen=false;
    //           }
    //
    // }
    // )
///////////////////////////////////Graphs//////////////////////////
let myChart= document.getElementById('myChart').getContext('2d');
let SalesChart= new Chart(myChart,{
  type:'bar',//bar,horitzontalBar, pie, line, doughnut, radar, polarArea
  data:{
    labels:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    datasets:[{
      label:'Monthly Sales 2019',
      data:[8000, 	7275, 	14625, 11925, 16350, 25700, 14750, 15225, 21875, 10900, 13400, 32225],
      // backgroundColor:'green'
      backgroundColor:['rgba(40, 210, 91, 0.4)','rgba(104, 13, 17, 0.2)','rgba(185, 132, 43, 0.3)','rgba(250, 99, 202, 0.8)','rgba(119, 72, 191, 1)','rgba(242, 43, 14, 0.3)','rgba(247, 26, 10, 0.9)','rgba(194, 117, 163, 0.9)','rgba(82, 217, 9, 0.1)','rgba(214, 177, 220, 1)','rgba(51, 250, 74, 0.8)','rgba(167, 191, 255, 1)','rgba(75, 25, 254, 0.8)']
    }]
  },
  options:{}
});
let costChart= document.getElementById('costChart').getContext('2d');
let lineChart= new Chart(costChart,{
  type:'line',//bar,horitzontalBar, pie, line, doughnut, radar, polarArea
  data:{
    labels:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    datasets:[{
      label:'Monthly Costs 2019',
      data:[6000, 	4275, 	5625, 9253, 2350, 3700, 4750, 5225, 6875, 7900, 8400, 9225],
      backgroundColor:'red'
    }]
  },
  options:{}
});


    </script>
  </body>
  </html>
